export enum AuditAction {
    // Authentication actions
    SIGN_IN = 'SIGN_IN',
    SIGN_UP = 'SIGN_UP',
    SIGN_OUT = 'SIGN_OUT',
    REFRESH_TOKEN = 'REFRESH_TOKEN',

    // Team actions
    CREATE_TEAM = 'CREATE_TEAM',
    UPDATE_TEAM = 'UPDATE_TEAM',
    DELETE_TEAM = 'DELETE_TEAM',
    ADD_TEAM_MEMBER = 'ADD_TEAM_MEMBER',
    REMOVE_TEAM_MEMBER = 'REMOVE_TEAM_MEMBER',
    UPDATE_TEAM_MEMBER_ROLE = 'UPDATE_TEAM_MEMBER_ROLE',

    // Project actions
    CREATE_PROJECT = 'CREATE_PROJECT',
    UPDATE_PROJECT = 'UPDATE_PROJECT',
    DELETE_PROJECT = 'DELETE_PROJECT',
    ADD_PROJECT_MEMBER = 'ADD_PROJECT_MEMBER',
    REMOVE_PROJECT_MEMBER = 'REMOVE_PROJECT_MEMBER',
    UPDATE_PROJECT_MEMBER_ROLE = 'UPDATE_PROJECT_MEMBER_ROLE',

    // Document actions
    CREATE_DOCUMENT = 'CREATE_DOCUMENT',
    UPDATE_DOCUMENT = 'UPDATE_DOCUMENT',
    DELETE_DOCUMENT = 'DELETE_DOCUMENT',
    VIEW_DOCUMENT = 'VIEW_DOCUMENT',

    // User actions
    UPDATE_USER = 'UPDATE_USER',
    DELETE_USER = 'DELETE_USER',
}
